/**
 * Account and session services.
 *
 * This module owns every rule about how an account is created, how a session is issued and rotated, and how a guest
 * identity becomes an account. The HTTP layer only translates requests into these calls and their typed failures back
 * into responses, so the rules can be tested without a socket in the way.
 *
 * The server is authoritative: nothing here trusts a client-supplied user id, status, or "authenticated" flag. A caller
 * proves who they are by presenting a token whose digest is stored against a live session.
 */

import { ACCOUNT_STATUS } from "./db.js";
import { AccountApiError, ErrorCode } from "./errors.js";
import {
  canonicalizeEmail,
  digestsMatch,
  isWellFormedDisplayName,
  isWellFormedEmail,
  isWellFormedGuestIdentity,
  newAccountId,
  newSessionId,
  newToken,
  tokenDigest,
} from "./ids.js";
import { hashPassword, performDummyVerification, validatePassword, verifyPassword } from "./passwords.js";

/** The account projection the API returns. Never contains a password hash, a digest, or a session token. */
function toPublicAccount(row) {
  return {
    userId: row.user_id,
    email: row.email,
    displayName: row.display_name,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function toPublicSession(row, tokens) {
  return {
    issuedAt: row.issued_at,
    accessExpiresAt: row.access_expires_at,
    refreshExpiresAt: row.refresh_expires_at,
    accessToken: tokens.accessToken,
    refreshToken: tokens.refreshToken,
  };
}

function nowIso() {
  return new Date().toISOString();
}

function isoFromNow(seconds) {
  return new Date(Date.now() + seconds * 1000).toISOString();
}

function isPast(isoTimestamp) {
  return Date.parse(isoTimestamp) <= Date.now();
}

function requireString(body, field) {
  const value = body?.[field];
  if (typeof value !== "string") throw new AccountApiError(ErrorCode.INVALID_REQUEST, `${field} must be a string`);
  return value;
}

// ---------------------------------------------------------------------------------------------------- guest identity

/**
 * Records an anonymous guest identity, or refreshes the timestamp of one already known.
 *
 * The identifier is generated by the app from a random source and carries no device identifier, advertising id, or
 * hardware fingerprint. The service stores the identifier, when it was first seen, and — after a conversion — which
 * account it belongs to. Nothing else, and no guest record is ever a credential: it cannot be used to sign in.
 */
export function recordGuestIdentity(database, guestIdentityId) {
  if (!isWellFormedGuestIdentity(guestIdentityId)) {
    throw new AccountApiError(ErrorCode.INVALID_GUEST_IDENTITY);
  }
  const timestamp = nowIso();
  const existing = database
    .prepare("SELECT guest_identity_id, created_at, linked_user_id FROM guest_identities WHERE guest_identity_id = ?")
    .get(guestIdentityId);
  if (existing) {
    database
      .prepare("UPDATE guest_identities SET last_seen_at = ? WHERE guest_identity_id = ?")
      .run(timestamp, guestIdentityId);
    return {
      guestIdentityId: existing.guest_identity_id,
      createdAt: existing.created_at,
      linked: existing.linked_user_id !== null,
    };
  }
  database
    .prepare(
      "INSERT INTO guest_identities (guest_identity_id, created_at, last_seen_at, linked_user_id, linked_at) VALUES (?, ?, ?, NULL, NULL)",
    )
    .run(guestIdentityId, timestamp, timestamp);
  return { guestIdentityId, createdAt: timestamp, linked: false };
}

/**
 * Links a guest identity to an account, exactly once.
 *
 * The rule is deterministic: an unknown identifier is recorded and linked, an unlinked identifier is linked, and an
 * identifier already linked to an account is refused with GUEST_IDENTITY_ALREADY_LINKED. Refusing is what prevents one
 * registration flow from producing two accounts — the caller is told which account already owns the identity instead of
 * a second account being created for it.
 */
function linkGuestIdentity(database, guestIdentityId, userId) {
  if (guestIdentityId === undefined || guestIdentityId === null) return false;
  if (!isWellFormedGuestIdentity(guestIdentityId)) {
    throw new AccountApiError(ErrorCode.INVALID_GUEST_IDENTITY);
  }
  const existing = database
    .prepare("SELECT linked_user_id FROM guest_identities WHERE guest_identity_id = ?")
    .get(guestIdentityId);
  if (existing?.linked_user_id !== null && existing?.linked_user_id !== undefined) {
    throw new AccountApiError(ErrorCode.GUEST_IDENTITY_ALREADY_LINKED);
  }
  const timestamp = nowIso();
  if (existing) {
    database
      .prepare("UPDATE guest_identities SET linked_user_id = ?, linked_at = ?, last_seen_at = ? WHERE guest_identity_id = ?")
      .run(userId, timestamp, timestamp, guestIdentityId);
  } else {
    database
      .prepare(
        "INSERT INTO guest_identities (guest_identity_id, created_at, last_seen_at, linked_user_id, linked_at) VALUES (?, ?, ?, ?, ?)",
      )
      .run(guestIdentityId, timestamp, timestamp, userId, timestamp);
  }
  return true;
}

// ------------------------------------------------------------------------------------------------------ sessions

function issueSession(database, configuration, userId, guestIdentityId = null) {
  const sessionId = newSessionId();
  const accessToken = newToken();
  const refreshToken = newToken();
  const issuedAt = nowIso();
  database
    .prepare(
      `INSERT INTO sessions
         (session_id, user_id, access_digest, refresh_digest, issued_at, access_expires_at, refresh_expires_at, revoked_at, guest_identity_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, NULL, ?)`,
    )
    .run(
      sessionId,
      userId,
      tokenDigest(configuration.authSecret, accessToken),
      tokenDigest(configuration.authSecret, refreshToken),
      issuedAt,
      isoFromNow(configuration.accessTokenTtlSeconds),
      isoFromNow(configuration.refreshTokenTtlSeconds),
      guestIdentityId,
    );
  return { accessToken, refreshToken, sessionId };
}

function loadLiveSession(database, configuration, { accessToken, refreshToken }) {
  const column = accessToken !== undefined ? "access_digest" : "refresh_digest";
  const token = accessToken !== undefined ? accessToken : refreshToken;
  if (typeof token !== "string" || token.length === 0) {
    throw new AccountApiError(ErrorCode.AUTHENTICATION_REQUIRED);
  }
  const digest = tokenDigest(configuration.authSecret, token);
  const row = database.prepare(`SELECT * FROM sessions WHERE ${column} = ?`).get(digest);
  if (!row) throw new AccountApiError(ErrorCode.SESSION_INVALID);
  if (!digestsMatch(row[column], digest)) throw new AccountApiError(ErrorCode.SESSION_INVALID);
  if (row.revoked_at !== null) throw new AccountApiError(ErrorCode.SESSION_INVALID);
  const expiresAt = accessToken !== undefined ? row.access_expires_at : row.refresh_expires_at;
  if (isPast(expiresAt)) throw new AccountApiError(ErrorCode.SESSION_EXPIRED);
  const user = database.prepare("SELECT * FROM users WHERE user_id = ?").get(row.user_id);
  if (!user) throw new AccountApiError(ErrorCode.SESSION_INVALID);
  if (user.status === ACCOUNT_STATUS.DELETED) throw new AccountApiError(ErrorCode.ACCOUNT_DELETED);
  if (user.status === ACCOUNT_STATUS.SUSPENDED) {
    revokeSession(database, row.session_id);
    throw new AccountApiError(ErrorCode.ACCOUNT_SUSPENDED);
  }
  return { row, user };
}

function revokeSession(database, sessionId) {
  database.prepare("UPDATE sessions SET revoked_at = ? WHERE session_id = ? AND revoked_at IS NULL").run(nowIso(), sessionId);
}

function revokeAllSessionsForUser(database, userId) {
  const result = database
    .prepare("UPDATE sessions SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL")
    .run(nowIso(), userId);
  return Number(result.changes ?? 0);
}

// ----------------------------------------------------------------------------------------------------- operations

/** Creates an account, then issues its first session. Both happen in one transaction. */
export async function registerAccount(database, configuration, body) {
  const email = requireString(body, "email").trim();
  const password = requireString(body, "password");
  const guestIdentityId = body.guestIdentityId ?? null;
  if (guestIdentityId !== null && !isWellFormedGuestIdentity(guestIdentityId)) {
    throw new AccountApiError(ErrorCode.INVALID_GUEST_IDENTITY);
  }
  if (!isWellFormedEmail(email)) throw new AccountApiError(ErrorCode.INVALID_EMAIL);
  const passwordCheck = validatePassword(password);
  if (!passwordCheck.valid) throw new AccountApiError(ErrorCode.INVALID_PASSWORD);
  const requestedName = body.displayName;
  if (!isWellFormedDisplayName(requestedName)) {
    throw new AccountApiError(ErrorCode.INVALID_DISPLAY_NAME);
  }

  const canonicalEmail = canonicalizeEmail(email);
  const existing = database.prepare("SELECT user_id FROM users WHERE email_canonical = ?").get(canonicalEmail);
  // A duplicate registration is refused before any guest link is written, so a rejected sign-up cannot consume the
  // guest identity and leave the user unable to convert it afterwards.
  if (existing) throw new AccountApiError(ErrorCode.ACCOUNT_ALREADY_EXISTS);

  const passwordHash = await hashPassword(password);
  const userId = newAccountId();
  const timestamp = nowIso();
  const displayName = requestedName.trim();

  database.exec("BEGIN IMMEDIATE");
  let tokens;
  let guestLinked = false;
  try {
    const duplicateAfterLock = database.prepare("SELECT user_id FROM users WHERE email_canonical = ?").get(canonicalEmail);
    if (duplicateAfterLock) throw new AccountApiError(ErrorCode.ACCOUNT_ALREADY_EXISTS);
    database
      .prepare(
        `INSERT INTO users (user_id, email, email_canonical, display_name, password_hash, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(userId, email.trim(), canonicalEmail, displayName, passwordHash, ACCOUNT_STATUS.ACTIVE, timestamp, timestamp);
    guestLinked = linkGuestIdentity(database, guestIdentityId, userId);
    tokens = issueSession(database, configuration, userId, guestIdentityId);
    database.exec("COMMIT");
  } catch (error) {
    database.exec("ROLLBACK");
    throw error;
  }

  const user = database.prepare("SELECT * FROM users WHERE user_id = ?").get(userId);
  const sessionRow = database.prepare("SELECT * FROM sessions WHERE session_id = ?").get(tokens.sessionId);
  return { account: toPublicAccount(user), session: toPublicSession(sessionRow, tokens), guestLinked };
}

/** Verifies credentials and issues a session. */
export async function login(database, configuration, body) {
  const email = requireString(body, "email").trim();
  const password = requireString(body, "password");
  const guestIdentityId = body.guestIdentityId ?? null;
  if (guestIdentityId !== null && !isWellFormedGuestIdentity(guestIdentityId)) {
    throw new AccountApiError(ErrorCode.INVALID_GUEST_IDENTITY);
  }
  if (!isWellFormedEmail(email)) throw new AccountApiError(ErrorCode.INVALID_EMAIL);
  if (password.length === 0) throw new AccountApiError(ErrorCode.INVALID_REQUEST, "password must not be empty");

  const user = database.prepare("SELECT * FROM users WHERE email_canonical = ?").get(canonicalizeEmail(email));
  if (!user || user.status === ACCOUNT_STATUS.DELETED) {
    // Same cost as a real verification, then the same error a wrong password produces: the service does not reveal
    // whether an address has an account.
    await performDummyVerification(password);
    throw new AccountApiError(ErrorCode.INVALID_CREDENTIALS);
  }
  const passwordMatches = await verifyPassword(password, user.password_hash);
  if (!passwordMatches) throw new AccountApiError(ErrorCode.INVALID_CREDENTIALS);
  if (user.status === ACCOUNT_STATUS.SUSPENDED) throw new AccountApiError(ErrorCode.ACCOUNT_SUSPENDED);

  database.exec("BEGIN IMMEDIATE");
  let tokens;
  try {
    // Signing in from a guest device links that anonymous identity to the account, once.
    try {
      linkGuestIdentity(database, guestIdentityId, user.user_id);
    } catch (error) {
      if (!(error instanceof AccountApiError) || error.code !== ErrorCode.GUEST_IDENTITY_ALREADY_LINKED) throw error;
      // Already linked — to this account or another. The sign-in itself still succeeds; nothing is rewritten.
    }
    tokens = issueSession(database, configuration, user.user_id, guestIdentityId);
    database.exec("COMMIT");
  } catch (error) {
    database.exec("ROLLBACK");
    throw error;
  }

  const sessionRow = database.prepare("SELECT * FROM sessions WHERE session_id = ?").get(tokens.sessionId);
  return { account: toPublicAccount(user), session: toPublicSession(sessionRow, tokens) };
}

/** Rotates a refresh token into a fresh pair, and is the only way a session outlives its access token. */
export function refreshSession(database, configuration, body) {
  const refreshToken = requireString(body, "refreshToken");
  let row;
  try {
    ({ row } = loadLiveSession(database, configuration, { refreshToken }));
  } catch (error) {
    if (error instanceof AccountApiError && error.code === ErrorCode.SESSION_INVALID) {
      throw new AccountApiError(ErrorCode.REFRESH_FAILED);
    }
    throw error;
  }

  const accessToken = newToken();
  const nextRefreshToken = newToken();
  const accessExpiresAt = isoFromNow(configuration.accessTokenTtlSeconds);
  const refreshExpiresAt = isoFromNow(configuration.refreshTokenTtlSeconds);
  const result = database
    .prepare(
      `UPDATE sessions
          SET access_digest = ?, refresh_digest = ?, access_expires_at = ?, refresh_expires_at = ?
        WHERE session_id = ? AND revoked_at IS NULL`,
    )
    .run(
      tokenDigest(configuration.authSecret, accessToken),
      tokenDigest(configuration.authSecret, nextRefreshToken),
      accessExpiresAt,
      refreshExpiresAt,
      row.session_id,
    );
  if (Number(result.changes ?? 0) === 0) throw new AccountApiError(ErrorCode.REFRESH_FAILED);

  const updated = database.prepare("SELECT * FROM sessions WHERE session_id = ?").get(row.session_id);
  return {
    session: {
      issuedAt: updated.issued_at,
      accessExpiresAt: updated.access_expires_at,
      refreshExpiresAt: updated.refresh_expires_at,
      accessToken,
      refreshToken: nextRefreshToken,
    },
  };
}

/**
 * Revokes the presented session.
 *
 * Revocation is idempotent from the caller's point of view: the same token cannot be revoked twice into an error.
 * Signing out never deletes builds, settings, provider credentials, or Minecraft pairing — those are not this service's
 * data and are never touched by it.
 */
export function logout(database, configuration, body) {
  const accessToken = typeof body?.accessToken === "string" ? body.accessToken : undefined;
  const refreshToken = typeof body?.refreshToken === "string" ? body.refreshToken : undefined;
  if (accessToken === undefined && refreshToken === undefined) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, "accessToken or refreshToken is required");
  }
  const digest = tokenDigest(configuration.authSecret, accessToken ?? refreshToken);
  const column = accessToken !== undefined ? "access_digest" : "refresh_digest";
  const row = database.prepare(`SELECT * FROM sessions WHERE ${column} = ?`).get(digest);
  if (!row) {
    // A token that matches nothing is already unusable; saying so is not a leak, and it keeps sign-out idempotent.
    return { revoked: false, alreadyRevoked: false, revokedSessions: 0 };
  }
  const alreadyRevoked = row.revoked_at !== null;
  revokeSession(database, row.session_id);
  return {
    // `revoked` states the outcome the client cares about: this session is not usable any more.
    revoked: true,
    alreadyRevoked,
    revokedSessions: alreadyRevoked ? 0 : 1,
  };
}

/** Returns the account behind an access token. The server decides validity; the client only caches the outcome. */
export function currentAccount(database, configuration, accessToken) {
  const { user, row } = loadLiveSession(database, configuration, { accessToken });
  return {
    account: toPublicAccount(user),
    session: { issuedAt: row.issued_at, accessExpiresAt: row.access_expires_at, refreshExpiresAt: row.refresh_expires_at },
  };
}

export { issueSession, revokeAllSessionsForUser, toPublicAccount };
