/**
 * Stable, typed errors for the account API. Messages contain no request data, credentials, SQL, or stack traces.
 */

export const ErrorCode = Object.freeze({
  // Request and transport
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_CONTENT_TYPE: "INVALID_CONTENT_TYPE",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CORS_ORIGIN_NOT_ALLOWED: "CORS_ORIGIN_NOT_ALLOWED",
  HTTPS_REQUIRED: "HTTPS_REQUIRED",
  RATE_LIMITED: "RATE_LIMITED",

  // Validation
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_DISPLAY_NAME: "INVALID_DISPLAY_NAME",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_DEVICE_LABEL: "INVALID_DEVICE_LABEL",

  // Account lifecycle
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Verification/recovery
  EMAIL_VERIFICATION_TOKEN_INVALID: "EMAIL_VERIFICATION_TOKEN_INVALID",
  EMAIL_VERIFICATION_TOKEN_EXPIRED: "EMAIL_VERIFICATION_TOKEN_EXPIRED",
  EMAIL_VERIFICATION_TOKEN_USED: "EMAIL_VERIFICATION_TOKEN_USED",
  PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID",
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  PASSWORD_RESET_TOKEN_USED: "PASSWORD_RESET_TOKEN_USED",
  CURRENT_PASSWORD_INVALID: "CURRENT_PASSWORD_INVALID",
  EMAIL_DELIVERY_UNAVAILABLE: "EMAIL_DELIVERY_UNAVAILABLE",

  // Sessions
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_INVALID: "SESSION_INVALID",
  REFRESH_FAILED: "REFRESH_FAILED",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  CURRENT_SESSION_REVOKE_NOT_ALLOWED: "CURRENT_SESSION_REVOKE_NOT_ALLOWED",

  // Guest identity
  INVALID_GUEST_IDENTITY: "INVALID_GUEST_IDENTITY",
  GUEST_IDENTITY_ALREADY_LINKED: "GUEST_IDENTITY_ALREADY_LINKED",

  // Legacy wire value retained so older service/client combinations can still interpret the pre-Phase-18 response.
  PASSWORD_RESET_NOT_IMPLEMENTED: "PASSWORD_RESET_NOT_IMPLEMENTED",

  // Developer control plane (separate from normal-user authentication)
  DEVELOPER_BOOTSTRAP_DISABLED: "DEVELOPER_BOOTSTRAP_DISABLED",
  DEVELOPER_BOOTSTRAP_INVALID: "DEVELOPER_BOOTSTRAP_INVALID",
  DEVELOPER_BOOTSTRAP_CONSUMED: "DEVELOPER_BOOTSTRAP_CONSUMED",
  DEVELOPER_INVALID_CREDENTIALS: "DEVELOPER_INVALID_CREDENTIALS",
  DEVELOPER_AUTHENTICATION_REQUIRED: "DEVELOPER_AUTHENTICATION_REQUIRED",
  DEVELOPER_SESSION_EXPIRED: "DEVELOPER_SESSION_EXPIRED",
  DEVELOPER_REFRESH_FAILED: "DEVELOPER_REFRESH_FAILED",
  DEVELOPER_ACCESS_DENIED: "DEVELOPER_ACCESS_DENIED",
  DEVELOPER_TOOL_UNKNOWN: "DEVELOPER_TOOL_UNKNOWN",
  DEVELOPER_TOOL_INPUT_INVALID: "DEVELOPER_TOOL_INPUT_INVALID",
  DEVELOPER_CONFIRMATION_INVALID: "DEVELOPER_CONFIRMATION_INVALID",
  DEVELOPER_CONFIRMATION_EXPIRED: "DEVELOPER_CONFIRMATION_EXPIRED",
  DEVELOPER_GRANT_ALREADY_ACTIVE: "DEVELOPER_GRANT_ALREADY_ACTIVE",
  DEVELOPER_GRANT_NOT_FOUND: "DEVELOPER_GRANT_NOT_FOUND",
  DEVELOPER_AI_UNAVAILABLE: "DEVELOPER_AI_UNAVAILABLE",
  DEVELOPER_AI_RESPONSE_INVALID: "DEVELOPER_AI_RESPONSE_INVALID",

  // Phase 22 membership, entitlement, and build-credit engine
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  ENTITLEMENT_REQUIRED: "ENTITLEMENT_REQUIRED",
  MEMBERSHIP_UNAVAILABLE: "MEMBERSHIP_UNAVAILABLE",
  CREDIT_OPERATION_INVALID: "CREDIT_OPERATION_INVALID",
  CREDIT_OPERATION_DUPLICATE: "CREDIT_OPERATION_DUPLICATE",
  CREDIT_OPERATION_CONFLICT: "CREDIT_OPERATION_CONFLICT",
  CREDIT_LEDGER_BUSY: "CREDIT_LEDGER_BUSY",

  // Phase 23 creator and server capability foundation
  CREATOR_ENTITLEMENT_REQUIRED: "CREATOR_ENTITLEMENT_REQUIRED",
  CREATOR_PROFILE_EXISTS: "CREATOR_PROFILE_EXISTS",
  CREATOR_PROFILE_NOT_FOUND: "CREATOR_PROFILE_NOT_FOUND",
  CREATOR_PROFILE_SUSPENDED: "CREATOR_PROFILE_SUSPENDED",
  CREATOR_HANDLE_UNAVAILABLE: "CREATOR_HANDLE_UNAVAILABLE",
  CREATOR_HANDLE_RESERVED: "CREATOR_HANDLE_RESERVED",
  CREATOR_VERIFICATION_REQUIRED: "CREATOR_VERIFICATION_REQUIRED",
  SERVER_ENTITLEMENT_REQUIRED: "SERVER_ENTITLEMENT_REQUIRED",
  SERVER_NOT_FOUND: "SERVER_NOT_FOUND",
  SERVER_ACCESS_DENIED: "SERVER_ACCESS_DENIED",
  SERVER_SUSPENDED: "SERVER_SUSPENDED",
  SERVER_LIMIT_REACHED: "SERVER_LIMIT_REACHED",
  SERVER_SLUG_RESERVED: "SERVER_SLUG_RESERVED",
  SERVER_SLUG_UNAVAILABLE: "SERVER_SLUG_UNAVAILABLE",
  OWNERSHIP_REQUIRED: "OWNERSHIP_REQUIRED",
  FEATURE_NOT_IMPLEMENTED: "FEATURE_NOT_IMPLEMENTED",
  STORAGE_BUSY: "STORAGE_BUSY",

  // Phase 24 buyer/seller onboarding
  PHONE_VERIFICATION_UNAVAILABLE: "PHONE_VERIFICATION_UNAVAILABLE",
  SELLER_AGREEMENT_REQUIRED: "SELLER_AGREEMENT_REQUIRED",

  // Phase 25 marketplace listings
  LISTING_NOT_FOUND: "LISTING_NOT_FOUND",
  LISTING_STATE_CONFLICT: "LISTING_STATE_CONFLICT",
  LISTING_PUBLISH_BLOCKED: "LISTING_PUBLISH_BLOCKED",

  // Phase 26 Hire a Builder
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_STATE_CONFLICT: "JOB_STATE_CONFLICT",
  PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
  PROPOSAL_STATE_CONFLICT: "PROPOSAL_STATE_CONFLICT",
  PROPOSAL_BLOCKED: "PROPOSAL_BLOCKED",

  // Phase 20 security event, incident, and automated response layer
  SECURITY_EVENT_INVALID: "SECURITY_EVENT_INVALID",
  SECURITY_ACTION_UNKNOWN: "SECURITY_ACTION_UNKNOWN",
  SECURITY_ACTION_NOT_AUTHORIZED: "SECURITY_ACTION_NOT_AUTHORIZED",
  SECURITY_ACTION_ARGUMENTS_INVALID: "SECURITY_ACTION_ARGUMENTS_INVALID",
  SECURITY_INCIDENT_NOT_FOUND: "SECURITY_INCIDENT_NOT_FOUND",
  SECURITY_ENGINE_UNAVAILABLE: "SECURITY_ENGINE_UNAVAILABLE",

  // Service
  NETWORK_ERROR: "NETWORK_ERROR",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
});

const STATUS_BY_CODE = Object.freeze({
  [ErrorCode.INVALID_REQUEST]: 400,
  [ErrorCode.INVALID_CONTENT_TYPE]: 415,
  [ErrorCode.REQUEST_TOO_LARGE]: 413,
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,
  [ErrorCode.CORS_ORIGIN_NOT_ALLOWED]: 403,
  [ErrorCode.HTTPS_REQUIRED]: 400,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.INVALID_EMAIL]: 400,
  [ErrorCode.INVALID_DISPLAY_NAME]: 400,
  [ErrorCode.INVALID_PASSWORD]: 400,
  [ErrorCode.INVALID_DEVICE_LABEL]: 400,
  [ErrorCode.ACCOUNT_ALREADY_EXISTS]: 409,
  [ErrorCode.ACCOUNT_NOT_FOUND]: 404,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.ACCOUNT_SUSPENDED]: 403,
  [ErrorCode.ACCOUNT_DELETED]: 403,
  [ErrorCode.EMAIL_NOT_VERIFIED]: 403,
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_INVALID]: 400,
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_EXPIRED]: 410,
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_USED]: 409,
  [ErrorCode.PASSWORD_RESET_TOKEN_INVALID]: 400,
  [ErrorCode.PASSWORD_RESET_TOKEN_EXPIRED]: 410,
  [ErrorCode.PASSWORD_RESET_TOKEN_USED]: 409,
  [ErrorCode.CURRENT_PASSWORD_INVALID]: 401,
  [ErrorCode.EMAIL_DELIVERY_UNAVAILABLE]: 503,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.SESSION_INVALID]: 401,
  [ErrorCode.REFRESH_FAILED]: 401,
  [ErrorCode.AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.SESSION_NOT_FOUND]: 404,
  [ErrorCode.CURRENT_SESSION_REVOKE_NOT_ALLOWED]: 409,
  [ErrorCode.INVALID_GUEST_IDENTITY]: 400,
  [ErrorCode.GUEST_IDENTITY_ALREADY_LINKED]: 409,
  [ErrorCode.PASSWORD_RESET_NOT_IMPLEMENTED]: 501,
  [ErrorCode.DEVELOPER_BOOTSTRAP_DISABLED]: 503,
  [ErrorCode.DEVELOPER_BOOTSTRAP_INVALID]: 401,
  [ErrorCode.DEVELOPER_BOOTSTRAP_CONSUMED]: 409,
  [ErrorCode.DEVELOPER_INVALID_CREDENTIALS]: 401,
  [ErrorCode.DEVELOPER_AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.DEVELOPER_SESSION_EXPIRED]: 401,
  [ErrorCode.DEVELOPER_REFRESH_FAILED]: 401,
  [ErrorCode.DEVELOPER_ACCESS_DENIED]: 403,
  [ErrorCode.DEVELOPER_TOOL_UNKNOWN]: 400,
  [ErrorCode.DEVELOPER_TOOL_INPUT_INVALID]: 400,
  [ErrorCode.DEVELOPER_CONFIRMATION_INVALID]: 400,
  [ErrorCode.DEVELOPER_CONFIRMATION_EXPIRED]: 410,
  [ErrorCode.DEVELOPER_GRANT_ALREADY_ACTIVE]: 409,
  [ErrorCode.DEVELOPER_GRANT_NOT_FOUND]: 404,
  [ErrorCode.DEVELOPER_AI_UNAVAILABLE]: 503,
  [ErrorCode.DEVELOPER_AI_RESPONSE_INVALID]: 502,
  [ErrorCode.SECURITY_EVENT_INVALID]: 400,
  [ErrorCode.SECURITY_ACTION_UNKNOWN]: 400,
  [ErrorCode.SECURITY_ACTION_NOT_AUTHORIZED]: 403,
  [ErrorCode.SECURITY_ACTION_ARGUMENTS_INVALID]: 400,
  [ErrorCode.SECURITY_INCIDENT_NOT_FOUND]: 404,
  [ErrorCode.SECURITY_ENGINE_UNAVAILABLE]: 503,
  // A credit shortfall and an unavailable plan are conflicts with current account state, not transport or server faults.
  [ErrorCode.INSUFFICIENT_CREDITS]: 409,
  [ErrorCode.ENTITLEMENT_REQUIRED]: 403,
  [ErrorCode.MEMBERSHIP_UNAVAILABLE]: 409,
  [ErrorCode.CREDIT_OPERATION_INVALID]: 400,
  [ErrorCode.CREDIT_OPERATION_DUPLICATE]: 409,
  [ErrorCode.CREDIT_OPERATION_CONFLICT]: 409,
  // Another writer holds the ledger lock past the busy timeout. Nothing was written; a retry with the same idempotency
  // key is always safe.
  [ErrorCode.CREDIT_LEDGER_BUSY]: 503,
  // Phase 23. An entitlement or ownership refusal is an authorization outcome; a missing resource is a not-found; a
  // suspended profile or workspace is a conflict with current state; a limit is a conflict with a configured bound.
  [ErrorCode.CREATOR_ENTITLEMENT_REQUIRED]: 403,
  [ErrorCode.CREATOR_PROFILE_EXISTS]: 409,
  [ErrorCode.CREATOR_PROFILE_NOT_FOUND]: 404,
  [ErrorCode.CREATOR_PROFILE_SUSPENDED]: 403,
  [ErrorCode.CREATOR_HANDLE_UNAVAILABLE]: 409,
  [ErrorCode.CREATOR_HANDLE_RESERVED]: 400,
  [ErrorCode.CREATOR_VERIFICATION_REQUIRED]: 403,
  [ErrorCode.SERVER_ENTITLEMENT_REQUIRED]: 403,
  [ErrorCode.SERVER_NOT_FOUND]: 404,
  [ErrorCode.SERVER_ACCESS_DENIED]: 403,
  [ErrorCode.SERVER_SUSPENDED]: 409,
  [ErrorCode.SERVER_LIMIT_REACHED]: 409,
  [ErrorCode.SERVER_SLUG_RESERVED]: 400,
  [ErrorCode.SERVER_SLUG_UNAVAILABLE]: 409,
  [ErrorCode.OWNERSHIP_REQUIRED]: 403,
  // 501 is the accurate answer: the service does not implement this capability yet, and saying so is the point.
  [ErrorCode.FEATURE_NOT_IMPLEMENTED]: 501,
  [ErrorCode.STORAGE_BUSY]: 503,
  // A phone field in an onboarding body is a request about a mechanism that does not exist: a validation refusal (400),
  // not a 501 for the endpoint — the endpoint works, the field is not part of it.
  [ErrorCode.PHONE_VERIFICATION_UNAVAILABLE]: 400,
  [ErrorCode.SELLER_AGREEMENT_REQUIRED]: 400,
  [ErrorCode.LISTING_NOT_FOUND]: 404,
  [ErrorCode.LISTING_STATE_CONFLICT]: 409,
  [ErrorCode.LISTING_PUBLISH_BLOCKED]: 403,
  [ErrorCode.JOB_NOT_FOUND]: 404,
  [ErrorCode.JOB_STATE_CONFLICT]: 409,
  [ErrorCode.PROPOSAL_NOT_FOUND]: 404,
  [ErrorCode.PROPOSAL_STATE_CONFLICT]: 409,
  [ErrorCode.PROPOSAL_BLOCKED]: 403,
  [ErrorCode.NETWORK_ERROR]: 503,
  [ErrorCode.BACKEND_UNAVAILABLE]: 503,
  [ErrorCode.UNKNOWN_ERROR]: 500,
});

const SAFE_MESSAGES = Object.freeze({
  [ErrorCode.INVALID_REQUEST]: "The request body is not valid JSON matching the contract.",
  [ErrorCode.INVALID_CONTENT_TYPE]: "This endpoint accepts JSON requests only.",
  [ErrorCode.REQUEST_TOO_LARGE]: "The request body is larger than this service accepts.",
  [ErrorCode.METHOD_NOT_ALLOWED]: "That method is not supported for this endpoint.",
  [ErrorCode.CORS_ORIGIN_NOT_ALLOWED]: "This origin is not allowed to call the account service.",
  [ErrorCode.HTTPS_REQUIRED]: "The account service requires a secure transport.",
  [ErrorCode.RATE_LIMITED]: "Too many attempts. Wait before trying again.",
  [ErrorCode.INVALID_EMAIL]: "That email address is not in a usable form.",
  [ErrorCode.INVALID_DISPLAY_NAME]: "That display name is not usable.",
  [ErrorCode.INVALID_PASSWORD]: "That password does not meet CraftMind's password requirements.",
  [ErrorCode.INVALID_DEVICE_LABEL]: "That device label is not usable.",
  [ErrorCode.ACCOUNT_ALREADY_EXISTS]: "An account already exists for that email address.",
  [ErrorCode.ACCOUNT_NOT_FOUND]: "No account matches that request.",
  [ErrorCode.INVALID_CREDENTIALS]: "The email address and password combination was not accepted.",
  [ErrorCode.ACCOUNT_SUSPENDED]: "This account is suspended and cannot sign in.",
  [ErrorCode.ACCOUNT_DELETED]: "This account is no longer available.",
  [ErrorCode.EMAIL_NOT_VERIFIED]: "Verify this email address before signing in.",
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_INVALID]: "That verification code is not valid.",
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_EXPIRED]: "That verification code has expired. Request a new one.",
  [ErrorCode.EMAIL_VERIFICATION_TOKEN_USED]: "That verification code has already been used.",
  [ErrorCode.PASSWORD_RESET_TOKEN_INVALID]: "That recovery code is not valid.",
  [ErrorCode.PASSWORD_RESET_TOKEN_EXPIRED]: "That recovery code has expired. Request a new one.",
  [ErrorCode.PASSWORD_RESET_TOKEN_USED]: "That recovery code has already been used.",
  [ErrorCode.CURRENT_PASSWORD_INVALID]: "The current password was not accepted.",
  [ErrorCode.EMAIL_DELIVERY_UNAVAILABLE]: "Email delivery is temporarily unavailable.",
  [ErrorCode.SESSION_EXPIRED]: "The session has expired. Sign in again.",
  [ErrorCode.SESSION_INVALID]: "The session is no longer valid. Sign in again.",
  [ErrorCode.REFRESH_FAILED]: "The session could not be refreshed. Sign in again.",
  [ErrorCode.AUTHENTICATION_REQUIRED]: "This endpoint requires a valid session.",
  [ErrorCode.SESSION_NOT_FOUND]: "That session is not available.",
  [ErrorCode.CURRENT_SESSION_REVOKE_NOT_ALLOWED]: "Use sign out to end the current session.",
  [ErrorCode.INVALID_GUEST_IDENTITY]: "That guest identity is not in the expected form.",
  [ErrorCode.GUEST_IDENTITY_ALREADY_LINKED]: "That guest identity is already linked to an account.",
  [ErrorCode.PASSWORD_RESET_NOT_IMPLEMENTED]: "Password reset is not implemented by this service yet.",
  [ErrorCode.DEVELOPER_BOOTSTRAP_DISABLED]: "Developer bootstrap is not enabled for this service.",
  [ErrorCode.DEVELOPER_BOOTSTRAP_INVALID]: "The one-time developer bootstrap authorization was not accepted.",
  [ErrorCode.DEVELOPER_BOOTSTRAP_CONSUMED]: "Developer bootstrap has already been consumed or is unavailable.",
  [ErrorCode.DEVELOPER_INVALID_CREDENTIALS]: "The developer email and password combination was not accepted.",
  [ErrorCode.DEVELOPER_AUTHENTICATION_REQUIRED]: "A valid developer session is required for this endpoint.",
  [ErrorCode.DEVELOPER_SESSION_EXPIRED]: "The developer session has expired. Sign in again.",
  [ErrorCode.DEVELOPER_REFRESH_FAILED]: "The developer session could not be refreshed. Sign in again.",
  [ErrorCode.DEVELOPER_ACCESS_DENIED]: "This developer role is not authorized for that action.",
  [ErrorCode.DEVELOPER_TOOL_UNKNOWN]: "That administrative tool is not registered.",
  [ErrorCode.DEVELOPER_TOOL_INPUT_INVALID]: "The administrative tool input does not match its schema.",
  [ErrorCode.DEVELOPER_CONFIRMATION_INVALID]: "That one-time action confirmation is invalid or already used.",
  [ErrorCode.DEVELOPER_CONFIRMATION_EXPIRED]: "That one-time action confirmation has expired. Prepare the action again.",
  [ErrorCode.DEVELOPER_GRANT_ALREADY_ACTIVE]: "That user already has an active grant for this entitlement.",
  [ErrorCode.DEVELOPER_GRANT_NOT_FOUND]: "That grant is not available.",
  [ErrorCode.DEVELOPER_AI_UNAVAILABLE]: "The Developer AI provider is not available in this service.",
  [ErrorCode.DEVELOPER_AI_RESPONSE_INVALID]: "The Developer AI returned a response outside the allowed tool contract.",
  [ErrorCode.SECURITY_EVENT_INVALID]: "That security signal is not in the accepted normalized form.",
  [ErrorCode.SECURITY_ACTION_UNKNOWN]: "That security response action is not registered.",
  [ErrorCode.SECURITY_ACTION_NOT_AUTHORIZED]: "The security policy did not authorize that response action.",
  [ErrorCode.SECURITY_ACTION_ARGUMENTS_INVALID]: "The security response arguments are outside their bounded schema.",
  [ErrorCode.SECURITY_INCIDENT_NOT_FOUND]: "That security incident is not available.",
  [ErrorCode.SECURITY_ENGINE_UNAVAILABLE]: "The security engine cannot be reached right now; existing protections still apply.",
  [ErrorCode.INSUFFICIENT_CREDITS]: "There are not enough build credits for this operation. Nothing was consumed.",
  [ErrorCode.ENTITLEMENT_REQUIRED]: "This account does not have the entitlement required for that operation.",
  [ErrorCode.MEMBERSHIP_UNAVAILABLE]: "That membership plan is not available on this deployment.",
  [ErrorCode.CREDIT_OPERATION_INVALID]: "The credit operation is not in the accepted form.",
  [ErrorCode.CREDIT_OPERATION_DUPLICATE]: "That idempotency key was already used for a different credit operation.",
  [ErrorCode.CREDIT_OPERATION_CONFLICT]: "The credit operation conflicts with the current ledger state and was refused.",
  [ErrorCode.CREDIT_LEDGER_BUSY]: "The credit ledger is busy with another operation. Nothing was charged; retry shortly.",
  [ErrorCode.CREATOR_ENTITLEMENT_REQUIRED]: "A creator entitlement is required for that operation. No plan is purchasable in this phase.",
  [ErrorCode.CREATOR_PROFILE_EXISTS]: "This account already has a creator profile.",
  [ErrorCode.CREATOR_PROFILE_NOT_FOUND]: "No creator profile matches that request.",
  [ErrorCode.CREATOR_PROFILE_SUSPENDED]: "This creator profile is not active, so protected creator operations are refused.",
  [ErrorCode.CREATOR_HANDLE_UNAVAILABLE]: "That creator handle is already taken.",
  [ErrorCode.CREATOR_HANDLE_RESERVED]: "That handle is reserved by the service and cannot be used.",
  [ErrorCode.CREATOR_VERIFICATION_REQUIRED]: "This operation requires a verified creator profile.",
  [ErrorCode.SERVER_ENTITLEMENT_REQUIRED]: "A server entitlement is required for that operation. No plan is purchasable in this phase.",
  [ErrorCode.SERVER_NOT_FOUND]: "No server workspace matches that request.",
  [ErrorCode.SERVER_ACCESS_DENIED]: "This account does not hold the role required for that server workspace.",
  [ErrorCode.SERVER_SUSPENDED]: "This server workspace is not active, so protected operations are refused. Its records are preserved.",
  [ErrorCode.SERVER_LIMIT_REACHED]: "This account has reached the configured limit for server workspaces.",
  [ErrorCode.SERVER_SLUG_RESERVED]: "That workspace address is reserved by the service and cannot be used.",
  [ErrorCode.SERVER_SLUG_UNAVAILABLE]: "That workspace address is already taken.",
  [ErrorCode.OWNERSHIP_REQUIRED]: "This account does not own the requested resource.",
  [ErrorCode.FEATURE_NOT_IMPLEMENTED]: "That capability is not implemented yet, so nothing was done.",
  [ErrorCode.STORAGE_BUSY]: "The service is busy with another write. Nothing was changed; retry shortly.",
  [ErrorCode.PHONE_VERIFICATION_UNAVAILABLE]: "Phone verification does not exist in CraftMind yet, so no phone number is accepted or treated as verified.",
  [ErrorCode.SELLER_AGREEMENT_REQUIRED]: "Accept the current creator agreement before completing seller onboarding.",
  [ErrorCode.LISTING_NOT_FOUND]: "That listing does not exist, or it is not available.",
  [ErrorCode.LISTING_STATE_CONFLICT]: "The listing is already in that state, so nothing was changed.",
  [ErrorCode.LISTING_PUBLISH_BLOCKED]: "Publishing needs an active creator profile, the Creator entitlement, and an accepted creator agreement. Complete seller onboarding first.",
  [ErrorCode.JOB_NOT_FOUND]: "That job does not exist, or it is not available.",
  [ErrorCode.JOB_STATE_CONFLICT]: "The job is no longer in the state this change requires, so nothing was changed.",
  [ErrorCode.PROPOSAL_NOT_FOUND]: "That proposal does not exist, or it is not available to you.",
  [ErrorCode.PROPOSAL_STATE_CONFLICT]: "The proposal or its job changed state, so nothing was changed.",
  [ErrorCode.PROPOSAL_BLOCKED]: "Proposals need an active creator profile, the Creator entitlement, and an accepted creator agreement. Complete seller onboarding first.",
  [ErrorCode.NETWORK_ERROR]: "The account service could not complete the network request.",
  [ErrorCode.BACKEND_UNAVAILABLE]: "The account service cannot serve this request right now.",
  [ErrorCode.UNKNOWN_ERROR]: "The account service could not complete this request.",
});

export class AccountApiError extends Error {
  constructor(code, message = SAFE_MESSAGES[code] ?? SAFE_MESSAGES[ErrorCode.UNKNOWN_ERROR], options = {}) {
    super(message);
    this.name = "AccountApiError";
    this.code = code;
    this.status = options.status ?? STATUS_BY_CODE[code] ?? 400;
    this.retryAfterSeconds = options.retryAfterSeconds;
  }
}

export { STATUS_BY_CODE, SAFE_MESSAGES };
