/**
 * Referral identifiers and marketing campaign attribution (Phase 32).
 *
 * This module is deliberately small, because the honest version of "marketing attribution" is small. It records two
 * things and nothing else: an account's own shareable referral code, and — for one referred account — which code was
 * used and which campaign the user named. It never records a URL, a query string, a device, a session, a cookie, or
 * anything observed about a person who has not stated it themselves.
 *
 * Design rules, in the same spirit as every earlier marketplace phase:
 *
 *   * **Identity is the session.** Every function takes the `userId` the API layer resolved from the bearer token.
 *     No endpoint accepts a `userId`, a `referralId`, an email, or a claimed "I am this account". A user therefore
 *     cannot impersonate a referrer: the referrer is whatever the *code* resolves to server-side, never a name the
 *     request supplied.
 *   * **A code is not a secret.** It is a shareable handle: knowing one lets a person attribute *their own* new
 *     account to you, and nothing more. So it is generated by the CSPRNG (`CM-` plus 12 hex characters — short enough
 *     to type, hex so it cannot be misread, and random so the namespace cannot be enumerated) rather than derived
 *     from an account id, email, or counter. Uniqueness is a database `UNIQUE` constraint on both sides, not a
 *     convention, and a collision retries rather than leaking which code was taken.
 *   * **The relationship is private to its two accounts.** No endpoint lists who used a code, and no response ever
 *     names the other party: a referrer sees only a *count* of attributed registrations, a referee sees only the code
 *     they themselves supplied. Aggregate marketing metrics stay category-level (see Phase 31 analytics) for the same
 *     reason. Nothing here is written to the audit log — copying a two-party relationship into a developer-visible
 *     log would widen exactly the privacy this phase is meant to protect.
 *   * **Attribution is one-per-account and immutable.** `referred_user_id` is UNIQUE, so each registration is
 *     counted once and a second, *different* claim is a typed conflict instead of a silent overwrite. Re-claiming the
 *     same code is an idempotent success so a double-submit cannot corrupt anything. A database trigger freezes every
 *     column except the one-way `OBSERVED -> VERIFIED` promotion, so the rule outlives this module.
 *   * **Observed is not verified.** A claim is *one party's assertion* that a code referred it; that is stored as
 *     `OBSERVED`. It becomes `VERIFIED` only when two independent server-side account facts both hold: the referred
 *     account has verified its own email (`users.email_verified_at`) and the referrer's account is live
 *     (`users.status = 'ACTIVE'`). `verified_at` then records the referred account's real verification timestamp, so
 *     the field is a fact that already existed, never a promotion stamp this module invented.
 *
 *     This conjunction is the definition that is actually reachable here, and it is worth stating why the obvious
 *     alternative is not: registration hands out **no** session and login is refused until the email is verified, so
 *     "a claim from an account that has not yet verified" cannot happen, and building a lifecycle stage around it
 *     would be a dead state with a test written to reach it by hand. What genuinely varies, and what marketing needs
 *     to know, is whether the *other* side of the relationship is real: a code whose owner has been suspended or
 *     deleted still records an honest attribution, but not a verified one. `POST /marketing/referrals/verify`
 *     re-evaluates the two facts and promotes; it is idempotent, needs no client claim of fact, and changes nothing
 *     about the verification endpoint's own behavior, ordering, or responses.
 *
 *     Verification is a historical record of the state at the time it was confirmed, not a live status — a later
 *     suspension does not rewrite history. Unverified attribution is reported as unverified in the API, in the
 *     metrics, and in the docs, and is never silently upgraded.
 *   * **No monetization, ever.** A referral here produces a recorded relationship and nothing else: no reward, no
 *     credit, no payout, no commission, no subscription, no entitlement, and no balance. Phases 28-29 stay deferred.
 */

import { AccountApiError, ErrorCode } from "./errors.js";
import { requireAccount } from "./entitlements.js";
import { REFERRAL_SOURCES } from "./onboarding.js";
import { newReferralAttributionId, newReferralCode, normalizeReferralCode } from "./ids.js";

/** Bounded, normalized campaign tokens. Lowercase alphanumerics plus `-`/`_` is all a label needs. */
export const REFERRAL_FIELD_LIMITS = Object.freeze({
  medium: { minimum: 1, maximum: 40 },
  campaign: { minimum: 1, maximum: 64 },
  code: { maximum: 64 },
});

/** Retry bound for the (astronomically unlikely) case a fresh code collides with an existing one. */
const CODE_ISSUE_ATTEMPTS = 8;

function nowIso(nowMillis) {
  return new Date(nowMillis).toISOString();
}

/**
 * Normalizes a campaign token: trim, collapse internal runs of whitespace to a single `-`, lowercase. The result must
 * match the stored `CHECK` shape exactly, so anything that could carry a URL, a query string, or a credential — a
 * `:`, `/`, `?`, `=`, `.`, or a non-ASCII lookalike — is refused rather than sanitized into storage.
 */
function normalizeCampaignToken(value, limit, field) {
  if (value === undefined || value === null) return null;
  if (typeof value !== "string") throw new AccountApiError(ErrorCode.INVALID_REQUEST, `${field} must be a string.`);
  const collapsed = value.trim().replace(/\s+/g, "-").toLowerCase();
  if (collapsed.length === 0) return null; // an all-blank token is "not provided", not an empty stored label
  if (collapsed.length < limit.minimum || collapsed.length > limit.maximum) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, `${field} must be ${limit.minimum}-${limit.maximum} characters after normalization.`);
  }
  if (field === "medium" ? !/^[a-z0-9][a-z0-9-]*$/.test(collapsed) : !/^[a-z0-9][a-z0-9_-]*$/.test(collapsed)) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, `${field} may contain only letters, digits, and ${field === "medium" ? "hyphens" : "hyphens or underscores"}.`);
  }
  return collapsed;
}

/**
 * Validates the attribution half of a request. `source` must be one of the existing onboarding answers, so campaign
 * reporting and the "how did you hear about us" survey speak one vocabulary instead of two. A claim that names no
 * source is labelled `FRIEND_REFERRAL` by the server: the only thing a code proves is that a person passed it on.
 */
function validateAttributionInput(body) {
  if (body === null || typeof body !== "object" || Array.isArray(body)) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST);
  }
  const source = body.source === undefined || body.source === null ? "FRIEND_REFERRAL" : body.source;
  if (typeof source !== "string" || !REFERRAL_SOURCES.includes(source)) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, `source must be one of: ${REFERRAL_SOURCES.join(", ")}.`);
  }
  return Object.freeze({
    source,
    medium: normalizeCampaignToken(body.medium, REFERRAL_FIELD_LIMITS.medium, "medium"),
    campaign: normalizeCampaignToken(body.campaign, REFERRAL_FIELD_LIMITS.campaign, "campaign"),
  });
}

/** Parses and validates a submitted code without touching the database: malformed input never becomes a lookup. */
function parseCodeInput(value) {
  const tooLong = typeof value === "string" && value.trim().length > REFERRAL_FIELD_LIMITS.code.maximum;
  const code = normalizeReferralCode(typeof value === "string" && !tooLong ? value : null);
  if (code === null) {
    // Deliberately identical to the response for "no such code", so the endpoint is not an existence oracle.
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, "That referral code was not recognized.");
  }
  return code;
}

/**
 * The two server-side facts that together make an attribution verified: the referred account has verified its own
 * email, and the referrer's account is live. Both are read from `users`; neither can be asserted by a client. A
 * referrer whose account is merely suspended keeps the attribution row (so the record is not lost) but keeps it
 * `OBSERVED`, which is exactly the distinction marketing should be allowed to see.
 */
function evaluateAttributionVerification(database, { referredUserId, referrerUserId }) {
  const referred = database.prepare("SELECT email_verified_at FROM users WHERE user_id = ?").get(referredUserId);
  const referrer = database.prepare("SELECT status FROM users WHERE user_id = ?").get(referrerUserId);
  const verifiedAt = typeof referred?.email_verified_at === "string" && referred.email_verified_at !== ""
    ? referred.email_verified_at
    : null;
  return verifiedAt !== null && referrer?.status === "ACTIVE"
    ? Object.freeze({ status: "VERIFIED", verifiedAt })
    : Object.freeze({ status: "OBSERVED", verifiedAt: null });
}

function attributionView(row) {
  return Object.freeze({
    attributionId: row.attribution_id,
    code: row.code,
    source: row.source,
    medium: row.medium,
    campaign: row.campaign,
    status: row.status,
    observedAt: row.observed_at,
    verifiedAt: row.verified_at,
    // What a referee is told about the referrer, in full: nothing. The relationship's other half is their own
    // private information to keep, and naming it here would let this endpoint enumerate accounts by code.
    referrerDisclosed: false,
  });
}

/* ------------------------------------------------------------------------------- code issuing */

/**
 * Returns the caller's own referral code, issuing one on first use. Idempotent: calling it again never rotates the
 * code, because a code a user has already shared must keep working.
 */
export function issueOrGetReferralCodeInTransaction(database, configuration, userId, { now = Date.now() } = {}) {
  requireAccount(database, userId);
  const existing = database.prepare("SELECT code, created_at FROM referral_codes WHERE user_id = ?").get(userId);
  if (existing) return Object.freeze({ code: existing.code, createdAt: existing.created_at, issuedNow: false });

  const timestamp = nowIso(now);
  for (let attempt = 0; attempt < CODE_ISSUE_ATTEMPTS; attempt += 1) {
    const candidate = newReferralCode();
    try {
      database.prepare("INSERT INTO referral_codes (code, user_id, created_at, updated_at) VALUES (?, ?, ?, ?)")
        .run(candidate, userId, timestamp, timestamp);
      return Object.freeze({ code: candidate, createdAt: timestamp, issuedNow: true });
    } catch (error) {
      // A second UNIQUE means this account already has a row after all (a racing self-request): return it. Anything
      // else is a genuine storage fault and must surface as one rather than as a retryable-looking rejection.
      const raced = database.prepare("SELECT code, created_at FROM referral_codes WHERE user_id = ?").get(userId);
      if (raced) return Object.freeze({ code: raced.code, createdAt: raced.created_at, issuedNow: false });
      if (!isUniqueViolation(error)) throw error;
    }
  }
  throw new AccountApiError(ErrorCode.STORAGE_BUSY, "Could not reserve a referral code right now. Please retry.");
}

/** A `UNIQUE` failure only — matched on SQLite's message, since the driver exposes no stable error code. */
function isUniqueViolation(error) {
  return typeof error?.message === "string" && /UNIQUE constraint failed/i.test(error.message);
}

/* ------------------------------------------------------------------------------- claim & promotion */

/**
 * Claims `referralCode` for the authenticated account. Atomic and single-shot: one row per referred account, the
 * referrer resolved from the code by the server, and the status decided from the account's *real* verification state.
 */
export function claimAttributionInTransaction(database, configuration, userId, body, { now = Date.now() } = {}) {
  requireAccount(database, userId);
  const attribution = validateAttributionInput(body);
  const code = parseCodeInput(body.referralCode);

  const row = database.prepare("SELECT user_id FROM referral_codes WHERE code = ?").get(code);
  if (!row || row.user_id === userId) {
    // Unknown and self-referential are answered identically: a caller learns only "that code does not work for you",
    // never whether the code exists, who owns it, or that they do.
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, "That referral code was not recognized.");
  }
  const referrerUserId = row.user_id;

  const existing = database.prepare("SELECT * FROM referral_attributions WHERE referred_user_id = ?").get(userId);
  if (existing) {
    if (existing.code === code) {
      // Re-claiming the same code is a no-op success, not an error: a refresh or double-submit must not corrupt or
      // re-stamp an attribution that is already recorded.
      return Object.freeze({ ...attributionView(existing), idempotent: true });
    }
    throw new AccountApiError(ErrorCode.REFERRAL_CLAIM_CONFLICT);
  }

  const timestamp = nowIso(now);
  const state = evaluateAttributionVerification(database, { referredUserId: userId, referrerUserId });
  const attributionId = newReferralAttributionId();
  try {
    database.prepare(
      `INSERT INTO referral_attributions
         (attribution_id, referred_user_id, referrer_user_id, code, source, medium, campaign, status, observed_at, verified_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    ).run(attributionId, userId, referrerUserId, code, attribution.source, attribution.medium, attribution.campaign,
      state.status, timestamp, state.verifiedAt);
  } catch (error) {
    // The racing write is the same account being claimed concurrently: converge on the row that won, unless the
    // winning code differs, in which case the caller's claim genuinely conflicted and nothing changed.
    const winner = database.prepare("SELECT * FROM referral_attributions WHERE referred_user_id = ?").get(userId);
    if (winner && winner.code === code) return Object.freeze({ ...attributionView(winner), idempotent: true });
    if (winner) throw new AccountApiError(ErrorCode.REFERRAL_CLAIM_CONFLICT);
    throw error;
  }
  return Object.freeze({
    attributionId, code, source: attribution.source, medium: attribution.medium, campaign: attribution.campaign,
    status: state.status, observedAt: timestamp, verifiedAt: state.verifiedAt,
    referrerDisclosed: false, idempotent: false,
  });
}

/**
 * Re-reads the two account facts and, if they now hold, promotes `OBSERVED` to `VERIFIED` in storage. A request
 * asserts nothing: this endpoint only asks the server to look at `users` again. It is idempotent in every direction
 * — re-confirming a verified attribution, or confirming one whose referrer is still suspended, is a success that
 * changes nothing — so a client may retry it safely and never sees an error it would have to interpret as a state.
 */
export function confirmAttributionInTransaction(database, configuration, userId, { now = Date.now() } = {}) {
  requireAccount(database, userId);
  const row = database.prepare("SELECT * FROM referral_attributions WHERE referred_user_id = ?").get(userId);
  if (!row) {
    throw new AccountApiError(ErrorCode.INVALID_REQUEST, "This account has no referral attribution to verify.");
  }
  if (row.status === "VERIFIED") return Object.freeze({ ...attributionView(row), promoted: false });

  const state = evaluateAttributionVerification(database, { referredUserId: userId, referrerUserId: row.referrer_user_id });
  if (state.status !== "VERIFIED") return Object.freeze({ ...attributionView(row), promoted: false });

  database.prepare("UPDATE referral_attributions SET status = 'VERIFIED', verified_at = ? WHERE attribution_id = ?")
    .run(state.verifiedAt, row.attribution_id);
  return Object.freeze({
    ...attributionView({ ...row, status: "VERIFIED", verified_at: state.verifiedAt }),
    promoted: true,
    promotedAt: nowIso(now),
  });
}

/* ------------------------------------------------------------------------------- self-service reads */

/** The caller's own code (if issued) plus their own inbound/outbound counts. Counts only — never identities. */
export function myReferralSummaryInTransaction(database, configuration, userId) {  requireAccount(database, userId);
  const codeRow = database.prepare("SELECT code, created_at FROM referral_codes WHERE user_id = ?").get(userId);
  const inbound = database.prepare(
    "SELECT status, COUNT(*) AS count FROM referral_attributions WHERE referred_user_id = ? GROUP BY status",
  ).all(userId);
  const inboundMap = Object.fromEntries(inbound.map((r) => [r.status, r.count]));
  const attributed = database.prepare(
    "SELECT status, COUNT(*) AS count FROM referral_attributions WHERE referrer_user_id = ? GROUP BY status",
  ).all(userId);
  const attributedMap = Object.fromEntries(attributed.map((r) => [r.status, r.count]));
  const own = database.prepare("SELECT * FROM referral_attributions WHERE referred_user_id = ?").get(userId);
  return Object.freeze({
    code: codeRow?.code ?? null,
    codeCreatedAt: codeRow?.created_at ?? null,
    // The attribution this account carries, if any. `referrerDisclosed: false` is not an oversight: the other half of
    // a referral relationship is never named back to either party through an API.
    attribution: own ? attributionView(own) : null,
    counts: Object.freeze({
      attributedRegistrations: Object.freeze({
        total: (attributedMap.OBSERVED ?? 0) + (attributedMap.VERIFIED ?? 0),
        observed: attributedMap.OBSERVED ?? 0,
        verified: attributedMap.VERIFIED ?? 0,
      }),
      received: Object.freeze({
        total: (inboundMap.OBSERVED ?? 0) + (inboundMap.VERIFIED ?? 0),
        observed: inboundMap.OBSERVED ?? 0,
        verified: inboundMap.VERIFIED ?? 0,
      }),
    }),
  });
}
